### ISSUE TITLE
Multiple Hash-Algorithm support

### ISSUE THREAD

**Issue by Hu6li** [hashlookup/hashlookup-forensic-analyser#14]
In order to enhance compatibility across multiple Hash-Sets it would be an improvement to support the specification of the hash algorithm to use.
Currently only Hash-Sets using SHA-1 are supported.

I suggest adding the possibility to specify the algorithm (supporting the currently most common algorithms)

**Comment by adulau** [comment]
Indeed good point. I'll have a look into. Thank you for the feedback.

**Comment by adulau** [comment]
Added via #16 and updated via https://github.com/hashlookup/hashlookup-forensic-analyser/commit/2560e3b6777ef0cae7d3af9ab06fcb57eb7a9670
