### ISSUE TITLE
Stream processing and cached/async lookups?

### ISSUE THREAD

**Issue by sthagen** [hashlookup/hashlookup-forensic-analyser#3]
I wonder if this script might be enhanced for use cases handling some or all of:

* large numbers of local objects
* high redundancy across execution runs or local folders in a single run
* low bandwidth uplinks

@adulau:  In case there is interest I am happy to provide a minimally invasive pull request (have to implement before ... of course).

Questions: 
1. Which python version is targeted as bottom? Is it 3.6+ or 3.8 or ...? 
   I do find indicators in the source but not declaration ... 
  I assume it is a version every analyst has on their OS but that I do not know :wink:
2. Could one use a bulk query endpoint as per "[Bulk search of SHA-1 hashes](https://circl.lu/services/hashlookup/#bulk-search-of-sha-1-hashes)"? 
3. Is this binary linux version compiled from the python source per nuitka, pythran et al. 
    or is this build from some other source language hosted elsewhere?

If it is compiled from python source I would need to know how, so I can provide a compilable version directly and no reviewer needs to hint me at all things breaking in that compilation.

**Comment by sthagen** [comment]
Unfortunately the python version is still often a marketing relevant question instead of simply following one or two versions behind the 3.x.0 version … 3.8 would be a very good target in my book.

Much work of walking the file tree is done by the operating system, and I know of companies that boost their databases by spidering over the columnar file storage.

Thank you for sharing these roadmap aspects and the generation scheme for the binary, much appreciated.

**Comment by adulau** [comment]
Bloom filter is now implemented to allow fast lookup without Internet access.
