### ISSUE TITLE
Missing dependency declaration of `pytz`

### ISSUE THREAD

**Issue by sthagen** [hashlookup/hashlookup-forensic-analyser#5]
# Why?

Without additionally installing `pytz` from pypi.org per pip the script does fail to start.

## What?

The `pytz`package is not part of the standard install of python but instead hosted on the Python Package Index at [pypi.org/project/pytz](https://pypi.org/project/pytz/)

Example failure:

```bash
$ python bin/hashlookup-analyser.py --include-stats -d . -v
Traceback (most recent call last):
  File "bin/hashlookup-analyser.py", line 11, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
```

### How?

Add the `pytz` dependency to the requirements file and maybe add an install section to the documentation.

The latter might go like this:

#### Install

```bash
$ pip install -r REQUIREMENTS
```

**Comment by adulau** [comment]
Thank you! It's a good catch. It's fixed.
