### ISSUE TITLE
Stuck at named pipes

### ISSUE THREAD

**Issue by michael-hamm** [hashlookup/hashlookup-forensic-analyser#8]
file=57C8EDB95DF3F0AD4EE2DC2B8CFD4157, mode=4607, finfo=os.stat_result(st_mode=4607, st_ino=10480, st_dev=1793, st_nlink=2, st_uid=0, st_gid=0, st_size=0, st_atime=1612118667, st_mtime=1612118667, st_ctime=1612118667)

file 57C8EDB95DF3F0AD4EE2DC2B8CFD4157
57C8EDB95DF3F0AD4EE2DC2B8CFD4157: fifo (named pipe)

**Comment by adulau** [comment]
Thank you for the report. It's fixed in 2c2ded2ba471f51b8c9da1a0859f61104074a19b, let me know it's fine for you.
